name: Fetch ICS
on:
  schedule:
    - cron: "15 15 * * *"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  j:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "hello"
